### ISSUE TITLE
Update config/app.yaml's default entry

### ISSUE THREAD

**Issue by DTasev** [DTasev/dawdle-client#35]
Remove the `chrome` entry in the config. Remove the `':'` from the except of the `default` entry, so that it looks like this:

```yaml
rules:
  default:
    separator: '-'
    reverse-search: true
    title-index: 1 # after separation the title will be index 1
    subtitle-index: 0 # this is the name of the tab that is being watched
    except: '' # if this is contained in the string, it will not be parsed further
```
